---
- hosts: ubuntu
  tasks:
   - name: cont
     community.general.docker_container:
       name: ubuntu-container
       image: ubuntu:latest
       command: sleep infinity

- hosts: webserver
  tasks:
    - name: nginx
      community.general.docker_container:
        name: nginx-server
        image: nginx:latest
        state: started
        ports:
          - 8080:80
