---
- name: Copiar inventory (copiar para as m치quinas ubuntu)
  hosts: ubuntu

  tasks:
    - name: Copiar arquivo do controlador para as m치quinas ubuntu
      copy:
        src: /root/arquivo-1.txt
        dest: /root/arquivo-2.txt
        remote_src: no

    - name: Copiar arquivo das m치quinas ubuntu para outra pasta nas mesmas m치quinas
      copy:
        src: /root/arquivo-2.txt
        dest: /tmp/arquivo-2.txt
        remote_src: yes
