---
- name: Atualizar cache dos SOs Alpine e Debian
  hosts: VMS
 
  tasks:
    - apk: update_cache=yes
      when: ansible_os_family == "Alpine"
   
    - apt: update_cache=yes
      when: ansible_os_family == "Debian"
